obj = input ('Digite algo: ')
print ('O tipo primitivo desse valor é: ',type(obj))
print (('Nome do objeto: {}').format(obj.format()))
print (('Númerico: {}').format((obj.isnumeric())))
print (('Letra: {}'.format(obj.isalpha())))
print (('Dígito: {}').format(obj.isdigit()))
print (('Espaço: {}'.format(obj.isspace())))
print (('Possui letra: {}'.format(obj.isidentifier())))
print (('Tem letra ou número (alfanumérico): {}'.format(obj.isalnum())))
print (('É formado de letras minúsculas: {}'.format(obj.islower())))
print (('Números positivos (???): {}'.format(obj.isdecimal())))